In [ ]:
import numpy as np

1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin


In [ ]:
arr1 = np.array([[[23,67,41],[78,92,38],[51,43,24]]])
arr1.ndim

3

2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.


In [ ]:
np.arange(34,113,6)

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)


In [ ]:
np.linspace(50,500,91, dtype = int)

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

4) 100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.


In [ ]:
np.logspace(102,105,8)

array([1.00000000e+102, 2.68269580e+102, 7.19685673e+102, 1.93069773e+103,
       5.17947468e+103, 1.38949549e+104, 3.72759372e+104, 1.00000000e+105])

5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.


In [ ]:
result = np.arange(0,9).reshape(3,3)

6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)



In [ ]:
np.zeros((6,6),dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)



In [ ]:
np.ones((4,4)).astype(int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)


In [ ]:
np.eye(8,8,0,int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)


In [ ]:
np.eye(5,5) * 3


array([[3., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 3.]])

10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.


In [ ]:
np.random.rand(6)

array([0.1867986 , 0.51579089, 0.94018815, 0.52974365, 0.464391  ,
       0.96460126])

11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.


In [ ]:
arr = np.random.randint(50,101,10).reshape(5,2)
print(arr)
print(f"Array boyutu = {arr.ndim}")

[[85 59]
 [86 93]
 [60 87]
 [59 58]
 [68 53]]
Array boyutu = 2


12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.


In [ ]:
np.random.randint(100,1000,50).reshape(2,5,5)

array([[[839, 620, 215, 466, 381],
        [988, 343, 615, 265, 686],
        [270, 519, 732, 627, 939],
        [215, 630, 270, 234, 203],
        [130, 250, 510, 260, 301]],

       [[157, 467, 942, 565, 663],
        [622, 866, 657, 625, 130],
        [883, 573, 316, 726, 483],
        [470, 847, 612, 358, 659],
        [200, 637, 760, 990, 533]]])

13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.


In [ ]:
randarr = np.random.randint(0,101,10)
print(randarr)
print(f"Max: {randarr.max()} , Index : {randarr.argmax()}")
print(f"Min: {randarr.min()} , Index : {randarr.argmin()}")

[31 52 33 73 46 10 69 38 77 59]
Max: 77 , Index : 8
Min: 10 , Index : 5


14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.


In [ ]:
manrandarr = np.random.randint(300,500,20).reshape(2,2,5)
manrandarr

array([[[362, 469, 405, 404, 325],
        [394, 421, 407, 499, 400]],

       [[453, 330, 321, 497, 470],
        [376, 321, 471, 444, 480]]])

In [ ]:
#Max
manrandarr[0][1][3]

499

In [ ]:
#Min
manrandarr[1][0][2]

321

15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.


In [ ]:
enarr = np.arange(0,51)
print(enarr)
enarr[20] = 500
enarr[35] = 500
print(enarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 500  21  22  23  24  25  26  27  28  29  30  31  32  33  34 500
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50]
