In [2]:
import numpy as np

1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.


In [ ]:
np.arange(0,30).reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [7]:
arr21 = np.random.randint(0,101,60).reshape(3,4,5)
print(arr21)
print(f"Boyutu: {arr21.ndim}")

[[[ 33  47  82  14  85]
  [ 11  30  51  29  60]
  [ 35  14  79  18  48]
  [ 74  22  15  33  34]]

 [[ 20  44  47  73   5]
  [  1  65  40  43  36]
  [ 92  12  49  87  75]
  [ 82  34  80   1   9]]

 [[ 19 100  61  13  77]
  [ 40  21  69  47  64]
  [ 88  14  83  49  30]
  [ 77   7   9  94  74]]]
Boyutu: 3


3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [12]:
arr31 = np.arange(20)
arr31.reshape(-1)
print(f"Boyutu: {arr31.ndim} , Shape'i: {arr31.shape}")

Boyutu: 1 , Shape'i: (20,)


4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.


In [15]:
arr41 = np.arange(4).reshape(2,2)
arr41

array([[0, 1],
       [2, 3]])

In [18]:
for i in arr41:
  for x in i:
    print(x)

0
1
2
3


In [16]:
for i in np.nditer(arr41):
  print(i)

0
1
2
3


5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.

In [ ]:
arr51 = np.array([5,10,15,20,25,30])
arr52 = np.array([1,2,3,4,5,6])
print(f"Toplama: {arr51[1] + arr52[2]}")
print(f"Çıkarma: {arr51[1] - arr52[2]}")
print(f"Çarpma: {arr51[1] * arr52[2]}")
print(f"Bölme: {arr51[1] / arr52[2]}")

Toplama: 13
Çıkarma: 7
Çarpma: 30
Bölme: 3.3333333333333335


6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.


In [21]:
arr61 = np.random.randint(0,101,10)
print(arr61)
print(arr61.sum())
print(arr61.mean())
print(arr61.max())
print(arr61.var())
print(arr61.std())

[83 41 42 76 24 20 77 49 94 15]
521
52.1
94
733.29
27.079327908941906


7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.


In [22]:
arr71 = np.arange(20)
arr72 = np.arange(500,531)
np.concatenate([arr71,arr72])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.


In [24]:
arr81 = np.arange(15,51)
arr82 = np.arange(10,101)
arr83 = np.concatenate([arr81,arr82])
arr81[25:51] = 888
arr81

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888])

9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.


In [26]:
arr91 = np.arange(0,40).reshape(8,5)
arr92 = np.arange(320,360).reshape(8,5)

In [28]:
np.concatenate([arr91,arr92], axis = 1)

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

In [29]:
np.concatenate([arr91,arr92], axis = 0)

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.


In [30]:
np.concatenate([arr91,arr92],axis=2)

AxisError: ignored

In [31]:
np.stack([arr91,arr92],axis=2)

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.


In [36]:
arr111 = np.array([1,20,25,4,4,5,4,4,1,6,9,12,1,5])
np.where(arr111 == 5)

(array([ 5, 13]),)

12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.


In [39]:
np.where(arr111 % 2 == 0)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.


In [40]:
np.where(arr111 > 4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.


In [41]:
np.where(arr111 % 5 == 0)

(array([ 1,  2,  5, 13]),)

15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin


In [43]:
arr151 = np.arange(85,101)
print(arr151)
np.random.choice(arr151)

[ 85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


93

16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.


In [45]:
np.random.randint(10,100,9).reshape(3,3)

array([[99, 88, 19],
       [46, 22, 91],
       [70, 36, 57]])

17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.


In [46]:
arr171 = np.arange(35,60)
np.random.choice(arr171)

39

18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.


In [76]:
arr181 = np.array([]) 
for i in range(10):
  arr181 = np.append(arr181,np.random.choice([3,8,10,53]))
arr181 = arr181.astype("int")
arr181.reshape(2,5)

array([[ 3, 53,  8,  8, 10],
       [ 3,  3, 53, 10,  8]])